Landing page
FuelupEducationIndia/fuelupeducation-react pull request #29
Opened 2021-04-08 09:46 UTC by fuelupeducation

2021-04-08 09:47 UTC, fuelupeducation commented
Conflict you can check kindly solve it

2021-04-08 13:41 UTC, Arboulahdour commented
This branch seems good to me.

2021-04-09 06:45 UTC, ArchitW requested changes

2021-04-09 06:45 UTC, ArchitW commented on src/components/UI/AppStore/AppStore.jsx
> +import GoogleStore from '../../../assets/images/group-54.png'
please use SVG's, rename the file as well if we already know its GoogleStore

2021-04-09 06:45 UTC, ArchitW commented on src/components/UI/AppStore/AppStore.jsx
> +import AppleStore from '../../../assets/images/group-57.png'
same as above

2021-04-09 06:45 UTC, ArchitW commented on src/components/UI/AppStore/AppStore.module.scss
> +    color: #978fb6;
can we have colors declarations globally, this will help us to use the strict color palette

2021-04-09 06:45 UTC, ArchitW commented on src/components/UI/AppStore/AppStore.module.scss
> +      color: #4a1d93;
can we have colors declarations globally, this will help us to use the strict color palette

2021-04-09 06:45 UTC, ArchitW commented on src/components/UI/Button/Button.module.scss
> +  border-radius: 2rem;
i see 2rem is getting used often can we create a global variable for it?

2021-04-09 06:45 UTC, ArchitW commented on src/components/UI/Button/Button.module.scss
> +    background: #f16600;
create a global variable

2021-04-09 06:45 UTC, ArchitW commented on src/components/UI/Button/Button.module.scss
> +    color: #fff;
create a global variable

2021-04-09 06:45 UTC, ArchitW commented on src/components/UI/Button/Button.module.scss
> +      background: #ff710c;
create a global variable

2021-04-09 06:45 UTC, ArchitW commented on src/components/UI/Social/Social.jsx
> +import Instagram from '../../../assets/images/instagram.png'
can we use SVG's for all images and icons?

2021-04-09 06:45 UTC, ArchitW commented on src/components/UI/Social/Social.module.scss
> +    color: #4a1d93;
create global variable for color

2021-04-09 06:45 UTC, ArchitW commented on src/components/icons/icons-svg/copyright.svg
> +<!-- Generator: Adobe Illustrator 17.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
clean up SVG

2021-04-09 06:45 UTC, ArchitW commented on src/pages/Landing/Landing.jsx
> +      <Course
create an array/object and loop them

2021-04-09 06:45 UTC, ArchitW commented on src/pages/Landing/Landing.module.scss
>    // background-image: linear-gradient(to bottom, #380885, #554cb8),
remove if not used

2021-04-09 06:45 UTC, ArchitW commented on src/pages/Landing/components/App/App.module.scss
> +      color: #4a1d93;
Please create global variable

2021-04-09 06:45 UTC, ArchitW commented on src/pages/Landing/components/Course/Course.module.scss
> +    color: #4a1d93;
add it in a global variable

2021-04-09 06:45 UTC, ArchitW commented on src/pages/Landing/components/Course/Course.module.scss
> +    color: #978fb6;
add it in a global variable

2021-04-09 06:45 UTC, ArchitW commented on src/pages/Landing/components/Footer/Footer.module.scss
> +  background: #faf9fc;
add it in a global variable

2021-04-09 06:45 UTC, ArchitW commented on src/pages/Landing/components/Footer/Footer.module.scss
> +      color: #978fb6;
add it in a global variable

2021-04-09 06:45 UTC, ArchitW commented on src/pages/Landing/components/Footer/Footer.module.scss
> +          fill: #978fb6;
add it in a global variable

2021-04-09 06:45 UTC, ArchitW commented on src/pages/Landing/components/Footer/Footer.module.scss
> +        color: #978fb6;
add it in a global variable

2021-04-09 06:45 UTC, ArchitW commented on src/pages/Landing/components/Footer/Footer.module.scss
> +        color: #4a1d93;
add it in a global variable

2021-04-09 06:45 UTC, ArchitW commented
Please resolve conflicts

2021-04-10 14:53 UTC, KhanhVanCong commented
I have pushed the code to refactor. @ArchitW Could you help me to review them?

2021-04-10 16:39 UTC, ArchitW commented
can you please help me to resolve conflicts?

2021-04-11 04:09 UTC, KhanhVanCong commented
Hi @ArchitW, During resolve the conflict, I found we have two main Page in the `src/pages/Landing/Landing.jsx`  and we have no other route for the Landing page, so what should I do now?

2021-04-12 03:11 UTC, ArchitW commented
> Hi @ArchitW, During resolve the conflict, I found we have two main Page in the `src/pages/Landing/Landing.jsx` and we have no other route for the Landing page, so what should I do now?

we should have only one main page

2021-04-12 03:21 UTC, KhanhVanCong commented
> > Hi @ArchitW, During resolve the conflict, I found we have two main Page in the `src/pages/Landing/Landing.jsx` and we have no other route for the Landing page, so what should I do now?
> 
> we should have only one main page

What is the page used? page in master or my branch?

2026-08-04 21:17 UTC, merged