New landingUi
FuelupEducationIndia/fuelupeducation-react pull request #33
Opened 2021-04-16 18:05 UTC by FizaWaseem

2021-04-17 17:46 UTC, ArchitW requested changes
Please remove empty files from the PR

2021-04-17 17:46 UTC, ArchitW commented on src/assets/styles/sass/_globalStyles.scss
> +  // width: 128rem;
remove commented code please

2021-04-17 17:46 UTC, ArchitW commented on src/assets/styles/sass/_mixin.scss
> +  color: $color;
from $colpr variable i am not able to guess the actual color. Please rename

2021-04-17 17:46 UTC, ArchitW commented on src/components/UI/LoadingSimple/LoadingSimple.js
> +// import './LoadingSimple.css'
remove commented code please

2021-04-17 17:46 UTC, ArchitW commented on src/pages/Landing/Landing.jsx
can we enable and use [sort-imports](https://marketplace.visualstudio.com/items?itemName=amatiasq.sort-imports#:~:text=Automatically%20sorts%20imports%20on%20save,Enter%20Sort%20imports)

2021-04-17 17:46 UTC, ArchitW commented on src/pages/Landing/Landing.jsx
> +        className="Course"
remove commented code Please

2021-04-17 17:46 UTC, ArchitW commented on src/pages/Landing/components/Footer/Footer.js
> +        </p>
`href="#about"` is placeholder? please use `#` if thats the case

2021-04-17 17:46 UTC, ArchitW commented on src/pages/Landing/components/Hero/Hero.module.scss
> +    color: #ffffff;
use variable for color

2021-04-17 17:46 UTC, ArchitW commented on src/pages/Landing/components/NavBar/NavBar.module.scss
> +  color: #ffffff !important;
1. use a variable for color. 
2. why there is a need to use !important can this be solved with [specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity)

2021-04-17 17:46 UTC, ArchitW commented on src/pages/Landing/components/NavBar/NavBar.module.scss
> +  color: #ffffff !important;
same as above

2021-04-17 17:46 UTC, ArchitW commented on src/pages/Landing/components/NavBar/NavBar.module.scss
> +    color: #ffffff;
same as above

2021-04-17 17:46 UTC, ArchitW commented on src/pages/Landing/components/NavBar/NavBar.module.scss
> +    color: #ffffff;
same as above

2021-04-17 17:46 UTC, ArchitW commented on src/pages/Landing/components/NavBar/NavBar.module.scss
> +    color: #f16600;
same as above use variable

2021-04-17 17:46 UTC, ArchitW commented on src/pages/Landing/components/NavBar/NavBar.module.scss
> +    border: solid .1rem #f16600;
use variable

2021-04-17 17:46 UTC, ArchitW commented on src/pages/Landing/components/NavBar/NavBar.module.scss
> +    background-color: #ffffff;
use variable

2021-04-17 17:46 UTC, ArchitW commented on src/pages/Landing/components/Places/Places.module.scss
> +      fill: #fff
use variable

2021-04-17 17:46 UTC, ArchitW commented
> _No description provided._

it would be nice if you provide few lines for this PR so that review can have some idea of what code they are reviewing

2021-04-20 15:23 UTC, ArchitW requested changes
1 comment please correct.
Rest of PR is LGTM

2021-04-20 15:23 UTC, ArchitW commented on src/pages/Landing/Landing.jsx
> +      </div>g
is this typo? remove g

2021-04-20 16:13 UTC, FizaWaseem commented
ok

2021-09-12 07:51 UTC, merged