Add files via upload
FuelupEducationIndia/fuelupeducation-react pull request #36
Opened 2021-05-26 19:42 UTC by UsmanMurtaza92

FuelUpEducation Student side complete

2021-06-02 17:48 UTC, ArchitW requested changes
Please use variables for colors that have used in the scss.
The rest of the PR looks okay to me.

2021-06-02 17:48 UTC, ArchitW commented on FuelUpEducation student-side/README.md
> +# Getting Started with Create React App
remove this default README

2021-06-02 17:48 UTC, ArchitW commented on FuelUpEducation student-side/public/index.html
> +      content="Web site created using create-react-app"
update content

2021-06-02 17:48 UTC, ArchitW commented on FuelUpEducation student-side/src/assets/styling/studentSide.scss
> +	background-color: #FAF9FE;
use variables for colors instead of adding theme as values

2021-06-02 17:48 UTC, ArchitW commented on FuelUpEducation student-side/src/assets/styling/studentSide.scss
> +	background-color: #FAF9FE;
same as above

2021-06-02 17:48 UTC, ArchitW commented on FuelUpEducation student-side/src/assets/styling/studentSide.scss
> +					color: #6440A3;
same as above

2021-06-02 17:48 UTC, ArchitW commented on FuelUpEducation student-side/src/assets/styling/studentSide.scss
> +			color: #6440A3;
same as above

2021-06-02 17:48 UTC, ArchitW commented on FuelUpEducation student-side/src/assets/styling/studentSide.scss
> +		background-color: #F5F4F4;
same as above

2021-06-02 17:48 UTC, ArchitW commented on FuelUpEducation student-side/src/assets/styling/studentSide.scss
> +			color: #F16600;
same as above

2021-06-02 17:48 UTC, ArchitW commented on FuelUpEducation student-side/src/assets/styling/studentSide.scss
> +				color: #F16600;
same as above

2021-06-02 17:48 UTC, ArchitW commented on FuelUpEducation student-side/src/assets/styling/studentSide.scss
> +						background-color: #3B0E8A;
same as above

2021-06-02 17:48 UTC, ArchitW commented on FuelUpEducation student-side/src/assets/styling/studentSide.scss
> +		color: #3B0E8A;
same as above

2021-06-02 17:48 UTC, ArchitW commented on FuelUpEducation student-side/src/assets/styling/studentSide.scss
> +			color: #FFC107;
same as above

2021-06-02 17:48 UTC, ArchitW commented on FuelUpEducation student-side/src/assets/styling/studentSide.scss
> +			color: #F16600;
same as above

2021-06-02 18:42 UTC, UsmanMurtaza92 commented
Ok

On Wed, Jun 2, 2021, 10:48 PM Archit Warghane ***@***.***>
wrote:

> *@ArchitW* requested changes on this pull request.
>
> Please use variables for colors that have used in the scss.
> The rest of the PR looks okay to me.
> ------------------------------
>
> In FuelUpEducation student-side/README.md
> <https://github.com/FuelupEducationIndia/fuelupeducation-react/pull/36#discussion_r644185763>
> :
>
> > @@ -0,0 +1,70 @@
> +# Getting Started with Create React App
>
> remove this default README
> ------------------------------
>
> In FuelUpEducation student-side/public/index.html
> <https://github.com/FuelupEducationIndia/fuelupeducation-react/pull/36#discussion_r644186234>
> :
>
> > @@ -0,0 +1,45 @@
> +<!DOCTYPE html>
> +<html lang="en">
> +  <head>
> +    <meta charset="utf-8" />
> +    <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
> +    <meta name="viewport" content="width=device-width, initial-scale=1" />
> +    <meta name="theme-color" content="#000000" />
> +    <meta
> +      name="description"
> +      content="Web site created using create-react-app"
>
> update content
> ------------------------------
>
> In FuelUpEducation student-side/src/assets/styling/studentSide.scss
> <https://github.com/FuelupEducationIndia/fuelupeducation-react/pull/36#discussion_r644187307>
> :
>
> > @@ -0,0 +1,1708 @@
> +* {
> +	// font-family: Muli Regular;
> +	box-sizing: border-box;
> +}
> +body {
> +	margin: 0;
> +	padding: 0;
> +	background-color: #FAF9FE;
>
> use variables for colors instead of adding theme as values
> ------------------------------
>
> In FuelUpEducation student-side/src/assets/styling/studentSide.scss
> <https://github.com/FuelupEducationIndia/fuelupeducation-react/pull/36#discussion_r644187531>
> :
>
> > @@ -0,0 +1,1708 @@
> +* {
> +	// font-family: Muli Regular;
> +	box-sizing: border-box;
> +}
> +body {
> +	margin: 0;
> +	padding: 0;
> +	background-color: #FAF9FE;
> +}
> +header {
> +	background-color: #FAF9FE;
>
> same as above
> ------------------------------
>
> In FuelUpEducation student-side/src/assets/styling/studentSide.scss
> <https://github.com/FuelupEducationIndia/fuelupeducation-react/pull/36#discussion_r644187972>
> :
>
> > +				i {
> +					font-size: 23px;
> +					color: silver;
> +					margin-right: 1.5rem;
> +				}
> +			}
> +			ul {
> +				list-style-type: none;
> +				margin-top: 1rem;
> +				margin-bottom: 2rem;
> +				padding-left: 0;
> +				li {
> +					margin: 5px 1rem;
> +					font-size: 22px;
> +					font-weight: bolder;
> +					color: #6440A3;
>
> same as above
> ------------------------------
>
> In FuelUpEducation student-side/src/assets/styling/studentSide.scss
> <https://github.com/FuelupEducationIndia/fuelupeducation-react/pull/36#discussion_r644188393>
> :
>
> > +		}
> +	}
> +	.nav-links {
> +		ul {
> +			display: flex;
> +			list-style-type: none;
> +		}
> +	}
> +}
> +.nav-links {
> +	ul {
> +		li {
> +			margin: 5px 1rem;
> +			font-size: 22px;
> +			font-weight: 1000;
> +			color: #6440A3;
>
> same as above
> ------------------------------
>
> In FuelUpEducation student-side/src/assets/styling/studentSide.scss
> <https://github.com/FuelupEducationIndia/fuelupeducation-react/pull/36#discussion_r644188871>
> :
>
> > +
> +.lecture-section {
> +	display: flex;
> +	justify-content: center;
> +	align-items: flex-start;
> +	// border: 2px solid red;
> +	.left-section {
> +		background-color: white;
> +		flex: 3;
> +		margin: 2rem;
> +		margin-bottom: 0;
> +		padding: 0 1rem;
> +		// border: 1px solid green;
> +	}
> +	.right-section {
> +		background-color: #F5F4F4;
>
> same as above
> ------------------------------
>
> In FuelUpEducation student-side/src/assets/styling/studentSide.scss
> <https://github.com/FuelupEducationIndia/fuelupeducation-react/pull/36#discussion_r644189122>
> :
>
> > +			margin-left: 1rem;
> +		}
> +	}
> +}
> +.left-section {
> +	.heading {
> +		display: flex;
> +		justify-content: flex-start;
> +		align-items: center;
> +		h2 {
> +			font-size: 30px;
> +			color: #6440A3;
> +			margin-right: 1rem;
> +		}
> +		span {
> +			color: #F16600;
>
> same as above
> ------------------------------
>
> In FuelUpEducation student-side/src/assets/styling/studentSide.scss
> <https://github.com/FuelupEducationIndia/fuelupeducation-react/pull/36#discussion_r644189299>
> :
>
> > +		}
> +		.select-share-options {
> +			position: absolute;
> +			top: 2.5rem;
> +			right: 1rem;
> +			padding: 1rem;
> +			width: 200px;
> +			background-color: white;
> +			border-radius: 5px;
> +			box-shadow: 0 0 4px 1px rgb(197, 196, 196);
> +			
> +			p {
> +				font-weight: normal;
> +				font-size: 13px;
> +				margin: 0;
> +				color: #F16600;
>
> same as above
> ------------------------------
>
> In FuelUpEducation student-side/src/assets/styling/studentSide.scss
> <https://github.com/FuelupEducationIndia/fuelupeducation-react/pull/36#discussion_r644189397>
> :
>
> > +						margin-right: 10px;
> +						font-size: 18px;
> +					}
> +				}
> +				.toggle-cam {
> +					margin-top: 5px;
> +					cursor: pointer;
> +					display: flex;
> +					justify-content: space-between;
> +					align-items: center;
> +					width: 100%;
> +					.toggler {
> +						// height: 22px;
> +						width: 45px;
> +						border-radius: 1rem;
> +						background-color: #3B0E8A;
>
> same as above
> ------------------------------
>
> In FuelUpEducation student-side/src/assets/styling/studentSide.scss
> <https://github.com/FuelupEducationIndia/fuelupeducation-react/pull/36#discussion_r644189675>
> :
>
> > +						.toggle-circle {
> +							height: 18px;
> +							width: 18px;
> +							border-radius: 50%;
> +							// border: 2px solid #3B0E8A;
> +							background-color: white;
> +						}
> +					}
> +				}
> +			}
> +		}
> +	}
> +}
> +.video-details {
> +	span {
> +		color: #3B0E8A;
>
> same as above
> ------------------------------
>
> In FuelUpEducation student-side/src/assets/styling/studentSide.scss
> <https://github.com/FuelupEducationIndia/fuelupeducation-react/pull/36#discussion_r644189737>
> :
>
> > +	}
> +}
> +.video-details {
> +	span {
> +		color: #3B0E8A;
> +		font-weight: 600;
> +	}
> +	.rating {
> +		margin-right: 1rem;
> +		display: flex;
> +		align-items: center;
> +		span {
> +			margin-right: 5px;
> +		}
> +		i {
> +			color: #FFC107;
>
> same as above
> ------------------------------
>
> In FuelUpEducation student-side/src/assets/styling/studentSide.scss
> <https://github.com/FuelupEducationIndia/fuelupeducation-react/pull/36#discussion_r644189837>
> :
>
> > +		margin-right: 1rem;
> +		display: flex;
> +		align-items: center;
> +		i {
> +			font-size: 22px;
> +			margin-right: 5px;
> +		}
> +	}
> +}
> +.screen-options {
> +	.recording {
> +		text-align: center;
> +		margin-right: 1rem;
> +		i {
> +			font-size: 20px;
> +			color: #F16600;
>
> same as above
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/FuelupEducationIndia/fuelupeducation-react/pull/36#pullrequestreview-674501782>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASDPB4R3C2JT5Z2BM66MUYTTQZVIHANCNFSM45SXWCAA>
> .
>

2021-06-04 17:11 UTC, ArchitW commented
Looks Good To Me. Please Merge 🚀

2021-06-04 20:44 UTC, merged

2021-06-04 20:47 UTC, UsmanMurtaza92 commented
Done.

On Fri, Jun 4, 2021 at 10:11 PM Archit Warghane ***@***.***>
wrote:

> Looks Good To Me. Please Merge 🚀
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/FuelupEducationIndia/fuelupeducation-react/pull/36#issuecomment-854882393>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASDPB4RHWNBTCOQ4JUITT3LTRECMXANCNFSM45SXWCAA>
> .
>